#!/bin/sh

# pmci
#
# Copyright 2018 Bill Zissimopoulos

# This file is part of "Poor Man's CI".
#
# It is licensed under the BSD license. The full license text can be found
# in the License.txt file at the root of this project.

ProgDir=$(cd $(dirname "$0") && pwd)
ProgName=$(basename "$0")

Help=""
for f in $(find $ProgDir -type f -name '*.shlib'); do
    . $f
done

if [ $# -eq 0 ]; then
    echo "usage: $ProgName COMMAND ARGS...\n" 1>&2
    echo "$Help" | while read name desc; do
        [ -n "$name" ] && echo "  ${name}\n    \t${desc}" 1>&2
    done
    exit 2
fi

# set -ex
"$@"
