hide footbox
skinparam BoxPadding 40

participant "<img:github.png>" as GitHub
box "Controller"
    participant Listener
    participant Scheduler
    participant Collector
end box
participant "Builder\nPool" as Pool

GitHub ->> Listener: push(repo)
activate Listener
deactivate Listener
loop retry delivery while\nno builder available
    Listener ->> Scheduler: work(repo)
    activate Scheduler
end
Pool ->> Scheduler: name
create builder
Scheduler -> builder: new(name, repo)
activate builder
deactivate Scheduler
builder -> builder: build(repo)
activate builder #Salmon
deactivate builder
builder ->> GitHub: status
builder ->> Collector: done(name)
destroy builder
activate Collector
Collector ->> Pool: name
deactivate Collector
note over builder #Salmon
    Salmon color:
    CI processing.
end note
